import 'package:wordle_flutter/features/keyboard/enums.dart';

final Map<String, LetterState> initialKeyboardState = {
  'A': LetterState.light,
  'B': LetterState.light,
  'C': LetterState.light,
  'Ç': LetterState.light,
  'D': LetterState.light,
  'E': LetterState.light,
  'F': LetterState.light,
  'G': LetterState.light,
  'Ğ': LetterState.light,
  'H': LetterState.light,
  'I': LetterState.light,
  'İ': LetterState.light,
  'J': LetterState.light,
  'K': LetterState.light,
  'L': LetterState.light,
  'M': LetterState.light,
  'N': LetterState.light,
  'O': LetterState.light,
  'Ö': LetterState.light,
  'P': LetterState.light,
  'R': LetterState.light,
  'S': LetterState.light,
  'Ş': LetterState.light,
  'T': LetterState.light,
  'U': LetterState.light,
  'Ü': LetterState.light,
  'V': LetterState.light,
  'Y': LetterState.light,
  'Z': LetterState.light,
};
