name: Dart Analysis and Lint Check

on:
  pull_request:
    branches:
      - master
      - action_test

jobs:
  analyze_and_lint_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get


      - name: Analyze and Lint Check
        run: flutter analyze --no-fatal-infos

