name: Dart Analysis and Lint Check

on:
  push:
    branches:
      - dev
      - action_test
  pull_request:
    branches:
      - dev
      - action_test

jobs:
  analyze_and_lint_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
#
#      - name: Setup Dart SDK
#        uses: dart-lang/setup-dart@v1
#        with:
#          sdk: stable

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze and Lint Check
        run: flutter analyze
