name: Dart Analysis and Lint Check

on:
  pull_request:
    branches:
      - master
      - action_test

jobs:
  analyze_and_lint_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get


      - name: Analyze and Lint Check
        run: flutter analyze --no-preamble --no-congratulate

      - name: Check Analysis Warnings and Errors
        run: |
          ANALYSIS_OUTPUT="$(flutter analyze --no-preamble --no-congratulate)"
          echo "$ANALYSIS_OUTPUT"
          if grep -q -E '^[ ]*[a-zA-Z0-9_\.\-]+:[0-9]+:[0-9]+(.*warning:|.*error:)' <<< "$ANALYSIS_OUTPUT"; then
            echo "Code analysis failed due to warnings or errors."
            exit 1
          else
            echo "Code analysis succeeded."
          fi
